version: '3.7'

services:
  
  localstack-s3:
    image: localstack/localstack:latest
    container_name: localstack-s3
    environment:
     - SERVICES=s3:4572,ssm:4583,dynamodb:4569
     - DATA_DIR=/tmp/localstack/data
    ports:
     - "4563-4599:4563-4599"
     - "9999:8080"
    volumes:
      - localstack-data:/tmp/localstack

volumes:

  localstack-data:
    name: localstack-data